name: Generate feeds and site

on:
  push:
    branches:
      - main
  schedule:
    # NOTE: UTCなので9時間引く
    # 平日 8~24時 10分。8~14時の1時間おき、16~24時の2時間おき
    - cron: 10 23,0-15 * * 1-5
    # 休日 8,10,12,14,16,18,20,22,24時 10分。8~24時の2時間おき
    - cron: 10 23,1,3,5,7,9,11,13,15 * * 0,6
  workflow_dispatch:

jobs:
  generate-feed:
    name: Generate Feed
    runs-on: ubuntu-20.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.4
          cache: yarn

      - name: Install node packages
        run: yarn install

      - name: Get date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache feed images
        uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ runner.os }}-feed-images-${{ steps.get-date.outputs.date }}

      - name: Generate feed
        run: yarn feed:generate

      - name: Generate site
        run: yarn site:build

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # NOTE: 変更履歴が必要な場合は false に変更
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
