name: Generate feeds

on:
  push:
    branches:
      - main
      # TODO: delete
      - feature/generate-feed
  schedule:
    # UTCなので9時間引く
    # 8,11,14,17,20時 の 10分
#    - cron: 10 23,2,5,8,11 * * *
    - cron: 10 23,0,1,2,3,4,5,6,7,8,9,10,11 * * *


jobs:
  generate-feed:
    name: Generate Feed
    runs-on: ubuntu-20.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          # TODO: main
          ref: feature/generate-feed

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.4

      - name: Install node packages
        run: yarn install

      - name: Generate feed
        run: yarn run generate-feed

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
