name: Generate feeds

on:
  push:
    branches:
      - main
  schedule:
    # NOTE: UTCなので9時間引く
    # 平日 8,10,12,14,16,18,20,22時 10分
    - cron: 10 23,1,3,5,7,9,11 * * 1-5
    # 休日 8,12,16,20時 10分
    - cron: 10 23,3,7,11 * * 0,6
  workflow_dispatch:

jobs:
  generate-feed:
    name: Generate Feed
    runs-on: ubuntu-20.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.4

      - name: Install node packages
        run: yarn install

      - name: Generate feed
        run: yarn build

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
